services:
  api:
    build:
      context: .
      target: development
    command: pnpm run start:dev
    depends_on:
      - mongodb
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
